### ISSUE TITLE
Missing index.php in root of swete install

### ISSUE THREAD

**Issue by andymelichar** [shannah/swete#12]
The instructions here: https://github.com/shannah/swete/blob/master/docs/phparch_article/page.markdown mention needing to add a rewrite to .htaccess to redirect all of requests to index.php, but there is no index.php included in the root directory of the swete install.

I may be missing something - but I can't figure out how swete is supposed to be processing requests at the target folder, it seems like there is a step missing from the install to explain/set this part up.

**Comment by shannah** [comment]
That rewrite rule was specific to proxying opencart.  What it does is convert requests for the root directory to index.php.  The rewrite rule 2 down, further rewrites it to go to the handler insider the swete-admin directory.

~~~~
RewriteEngine On
RewriteRule ^$ index.php    # Converts things like http://example.com/ to http://example.com/index.php
RewriteRule ^swete-admin/ - [L,NC]  # prevents rewriting URLs specifically to the swete-admin directory
RewriteRule . swete-admin/index.php?-action=swete_handle_request [L]   # passes all requests to swete handler.
~~~~
